#define DID_MixerWindow             1000
#define DID_MASTERL                 1002
#define DID_MASTERR                 1003
#define DID_MASTERLOCK              1004
#define DID_VOICEL                  1006
#define DID_VOICER                  1007
#define DID_VOICELOCK               1008
#define DID_FML                     1010
#define DID_FMR                     1011
#define DID_FMLOCK                  1012
#define DID_CDL                     1014
#define DID_CDR                     1015
#define DID_CDLOCK                  1016
#define DID_LINEL                   1018
#define DID_LINER                   1019
#define DID_LINELOCK                1020
#define DID_SPK                     1024
#define DID_BASSL                   1026
#define DID_BASSR                   1027
#define DID_BASSLOCK                1028
#define DID_TREBLEL                 1030
#define DID_TREBLER                 1031
#define DID_TREBLELOCK              1032
#define DID_BASEPORT                1035
#define DID_AUTOSET                 1037
#define DID_AUTOREAD                1022
#define DID_MICLOCK                 1036
#define DID_MICR                    1038
#define DID_MICL                    1039
